# Application properties

# Server Configuration
server.port=8080
spring.application.name=springboot-interview
spring.main.allow-bean-definition-overriding=true


# Database Configuration (H2 In-Memory Database)
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Enable H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Actuator Configuration
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.health.redis.enabled=false

# Kafka Configuration
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=interview-group
spring.kafka.listener.auto-startup=false

# Logging Configuration (includes MDC transactionId)
logging.pattern.console=%d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX} %5p [%t] [%X{transactionId}] %c{1.} : %m%n


# Redis Configuration
spring.data.redis.host=localhost
spring.data.redis.port=6379

# Security Configuration
spring.security.user.name=admin
spring.security.user.password=admin
